forum/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from forum import views

urlpatterns = [
    # ajax_views
    url(r'ajax/add_chat_message/$', views.add_chat_message, name='add_chat_message'),
    url(r'ajax/refresh_chat/$', views.refresh_chat, name='refresh_chat'),
    url(r'ajax/update_likes/$', views.update_likes, name='update_likes'),

    # login views
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^logout-then-login/$',
        auth_views.logout_then_login, name='logout_then_login'),

    # edit views
    url(r'^edit/$', views.edit, name='edit'),

    # register views
    url(r'^register/$', views.register, name='register'),

    # password views
    url(r'^password-change/$', auth_views.password_change, name='password_change'),
    url(r'^password-change/done/$', auth_views.password_change_done, name='password_change_done'),

    # reset password
    url(r'^password-reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password-reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+/$)',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^password-reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # section views
    url(r'^$', views.section_list, name='section_list'),
    url(r'^(?P<section>[-\w]+)/$', views.section_detail, name='section_detail'),

    # topic views
    url(r'^(?P<section>[-\w]+)/add_topic/$', views.add_topic, name='add_topic'),
    url(r'^(?P<section>[-\w]+)/(?P<topic>[-\w]+)/$', views.topic_detail, name='topic_detail'),

    # post views
    url(r'^(?P<section>[-\w]+)/(?P<topic>[-\w]+)/add_post/$', views.add_post, name='add_post'),

]

mainsite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^forum/', include('django.contrib.auth.urls')),
    url(r'^forum/', include('forum.urls',
                            namespace='forum',
                            app_name='forum')),
    url(r'^inbox/', include('inbox.urls',
                            namespace='inbox',
                            app_name='inbox')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Post, Profile, Topic


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content',)


class AddTopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ('title',)


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

forum/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Max, Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect

from .forms import AddPostForm, AddTopicForm, LoginForm, ProfileEditForm, \
    UserEditForm, UserRegistrationForm
from .models import Section, Topic, Post, Profile, Message

import json
import redis

# connect to redis
r = redis.StrictRedis(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)

# section views
def section_list(request):
    sections = Section.members.all()
    return render(request,
                  'forum/section_list.html',
                  {'sections': sections})


def section_detail(request, section):
    section = get_object_or_404(Section,
                                slug=section)
    # annotate each topic with its latest post and order the topics
    # by most recent post
    topic_list = Topic.objects.filter(
        section=section).annotate(
        latest_post=Max(
            'topic_posts__created')).order_by('-latest_post')
    paginator = Paginator(topic_list, 5)
    page = request.GET.get('page')
    try:
        topics = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer then deliver the first page
        topics = paginator.page(1)
    except EmptyPage:
        # If page is out of range then deliver the last page
        topics = paginator.page(paginator.num_pages)

    return render(request,
                  'forum/section_detail.html',
                  {'section': section,
                   'page': page,
                   'topics': topics})


# topic views
def topic_detail(request, section, topic):
    section = get_object_or_404(Section,
                                slug=section)
    topic = get_object_or_404(Topic,
                              section=section,
                              slug=topic)
    # increment the total views by 1
    r.incr('topic:{}:views'.format(topic.id))
    post_list = Post.objects.filter(topic=topic)
    paginator = Paginator(post_list, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer then deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range then deliver the last page
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'forum/topic_detail.html',
                  {'section': section,
                   'topic': topic,
                   'page': page,
                   'posts': posts})


@login_required
def add_topic(request, section):
    if request.method == 'POST':
        topic_form = AddTopicForm(request.POST)
        post_form = AddPostForm(request.POST)
        if topic_form.is_valid() and post_form.is_valid():
            cd_topic_form = topic_form.cleaned_data
            cd_post_form = post_form.cleaned_data

            # assign user and section to new topic
            new_topic = topic_form.save(commit=False)
            new_post = post_form.save(commit=False)

            topic_section = get_object_or_404(Section,
                                              slug=section)
            new_topic.owner = request.user
            new_topic.section = topic_section
            new_topic.save()

            # assign user and topic to opening post
            new_post.owner = request.user
            new_post.topic = new_topic
            new_post.save()

            return redirect('forum:section_detail', section)
    else:
        topic_form = AddTopicForm
        post_form = AddPostForm

    return render(request, 'forum/add_topic.html',
                  {'topic_form': topic_form,
                   'post_form': post_form})


# registration views
def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # create a new user object but don't save
            new_user = user_form.save(commit=False)
            # set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # save the user
            new_user.save()
            # create the user profile
            profile = Profile.objects.create(user=new_user)
            return render(request,
                          'registration/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm
    return render(request,
                  'registration/register.html',
                  {'user_form': user_form})

# login views
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                                password=cd['password'])
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


# post views
@login_required
def add_post(request, section, topic):
    if request.method == 'POST':
        form = AddPostForm(data=request.POST)
        if form.is_valid():
            # form data is valid
            cd = form.cleaned_data
            new_post = form.save(commit=False)

            # assign current user and topic to post
            post_section = get_object_or_404(Section,
                                             slug=section)
            post_topic = get_object_or_404(Topic,
                                           section=post_section,
                                           slug=topic)

            new_post.owner = request.user
            new_post.topic = post_topic

            # save the post
            new_post.save()

            return redirect('forum:topic_detail', section, topic)
    else:
        form = AddPostForm

    return render(request,
                  'forum/add_post.html',
                  {'form': form})

def update_likes(request):

    if request.method == 'POST':
        response_data = {}
        post_id = request.POST.get('post_id')
        post_action = request.POST.get('post_action')

        post = Post.objects.get(id=post_id)
        user = request.user
        if post.owner != user:

            if post_action == 'like':
                post.likes.add(user)
            else:
                post.likes.remove(user)
            post.save()

            response_data['result'] = 'updated'
            response_data['post_id'] = post.pk
            response_data['users_like'] = list(post.likes.all().values_list('username', flat=True))
            response_data['post_likes'] = post.likes.count()

            return HttpResponse(json.dumps(response_data),
                                content_type='application/json')
        else:
            return HttpResponse({'result': 'not updated'},
                                content_type='application/json')
    else:
        return HttpResponse({'result': 'not updated'},
                            content_type='application/json')
# chat views
def add_chat_message(request):

    if request.method == 'POST':
        message_text = request.POST.get('chat_message_text')
        if message_text:
            user = request.user
            response_data = {}

            new_message = Message.objects.create(content=message_text,
                                                 owner=user)
            new_message.save()

            response_data['result'] = 'created'
            response_data['message_pk'] = new_message.pk
            response_data['text'] = new_message.content
            response_data['created'] = new_message.created.strftime('%b %d, %Y %I:%M %p')
            response_data['owner'] = new_message.owner.username

            return HttpResponse(json.dumps(response_data),
                                content_type='application/json')
        else:
            return HttpResponse(json.dumps({'result': 'not created'}),
                                content_type='application/json')
    else:
        return HttpResponse(json.dumps({'result': 'not created'}),
                            content_type='application/json')

def refresh_chat(request):

    if request.method == 'POST':

        last_message = Message.objects.latest('created').content
        last_chat_message = request.POST.get('last_message')

        # check whether any new chat messages have been added
        if last_message != last_chat_message:
            response_data = {}

            # display the last five chat messages only
            messages = Message.objects.all()
            # need to convert to a list to use negative indexing
            last_ten_messages = list(messages.values('owner__username', 'created', 'content'))[-10:]
            last_ten_messages.reverse()
            for idx, message in enumerate(last_ten_messages):
                last_ten_messages[idx]['created'] = message['created'].strftime('%b %d, %Y %I:%M %p')

            response_data['result'] = 'refreshed'
            response_data['messages'] = last_ten_messages

            return HttpResponse(json.dumps(response_data),
                                content_type='application/json')
        else:
            return HttpResponse(json.dumps({'result': 'not refreshed'}),
                                content_type='application/json')
    else:

forum/templates/base.html
{% load forum_tags %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static  'css/forum.css' %}" type="text/css" rel="stylesheet" />
    </head>
    <body>
    <div id="navigation">
        {% if request.user.is_authenticated %}
            <a href="{% url 'inbox:inbox' %}">Inbox</a>
        {% endif %}
    </div>
	<div id="header">
	    {% if request.user.is_authenticated %}
	    Welcome {{ request.user.username }}
	    <a href="{% url 'forum:logout' %}">[Logout]</a> |
	    <a href="{% url 'forum:edit' %}">[Edit profile]</a>
	    {% else %}
	    <a href="{% url 'forum:login' %}">[Log-in]</a> |
	    <a href="{% url 'forum:register' %}">[Sign-up]</a>
	    {% endif %}
    </div>
    <div id="wrapper">
        <div id="title">
            <h1>League of Casuals!</h1>
        </div>
        <div id="jump_menu">
            {% jump_menu %}
        </div>
        <div id="chat">
            {% chat_messages %}
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <div id="sidebar">
            <h2>Forum Stat's</h2>
            <div id="top_three_poster">
                <h3>Today's Top 3 Posters</h3>
                {% top_three_posters as top_posters %}
                <ul class="top_three_posters">
                    {% for poster in top_posters %}
                        <li>{{ poster|capfirst }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div id="top_three_topics">
                <h3>Hot Topics</h3>
                {% top_three_topics as top_topics %}
                <ul class="top_three_topics">
                    {% for topic in top_topics %}
                        <li><a href="{% url 'forum:topic_detail' topic.section.slug topic.slug %}">{{ topic|capfirst }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div id="footer">
            <div id="online_members">
                {% online_members as online_members %}
                    Members Online:
                    {% for member in online_members %}
                        {% if forloop.last %}
                            {{ member }}
                        {% else %}
                            {{ member }},
                        {% endif %}
                    {% endfor %}
            </div>
            <div id="board_statistics">
                Total Members: {% total_members %} (Newest Member: {% newest_member %}) <br/>
                Total Forum Posts: {% total_posts %}
            </div>
        </div>
    </div><!--wrapper-->
        <script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
        <script src="{% static 'js/jquery.cookie.min.js' %}"></script>
        <script src="{% static 'js/check_csrf_token.js' %}"></script>
        <script src="{% static 'js/forum_scripts.js' %}"></script>
    </body>
</html>

forum/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {%  endif %}
    </span>
</div>